
SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER CLIENTS
BEFORE INSERT ON CLIENTS
FOR EACH ROW
BEGIN
    :NEW.ID_CLIENT :=CLIENTS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER MATERIALS
BEFORE INSERT ON MATERIALS
FOR EACH ROW
BEGIN
    :NEW.ID_PLATE :=MATERIALS_SEQ.NEXTVAL;
END;

/
CREATE OR REPLACE TRIGGER ORDERS
BEFORE INSERT ON ORDERS
FOR EACH ROW
BEGIN
    :NEW.ID_ORDER :=ORDERS_SEQ.NEXTVAL;
END;
/

