
SET SERVEROUTPUT ON;

-- CLIENTS TABLE TRIGGERS

CREATE OR REPLACE TRIGGER CLIENTS
BEFORE INSERT ON CLIENTS
FOR EACH ROW
BEGIN
    :NEW.ID_CLIENT :=CLIENTS_SEQ.NEXTVAL;
END;
/

-- MATERIALS TABLE TRIGGERS

CREATE OR REPLACE TRIGGER MATERIALS
BEFORE INSERT ON MATERIALS
FOR EACH ROW
BEGIN
    :NEW.ID_PLATE :=MATERIALS_SEQ.NEXTVAL;
END;

/

-- ORDERS TABLE TRIGGERS

CREATE OR REPLACE TRIGGER ORDERS
BEFORE INSERT ON ORDERS
FOR EACH ROW
BEGIN
    :NEW.ID_ORDER :=ORDERS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER ORDERS_SEND
AFTER INSERT ON ORDERS
FOR EACH ROW
DECLARE
  ORDERS_NUMBER  NUMBER;
BEGIN
    SELECT COUNT(*) INTO ORDERS_NUMBER FROM ORDERS;
    
    IF(ORDERS_NUMBER>10) THEN
    DBMS_OUTPUT.PUT_LINE('10 ORDERS -> PROCESS');
    END IF;
END;
/

